language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
script:
  - bash -ex .travis-ocaml.sh
  - eval $(opam config env)
  - opam install --yes dune alcotest alcotest-lwt digestif cmdliner fmt irmin irmin-unix logs lwt ocamlgraph
  - git clone https://github.com/mirage/irmin
  - opam pin ./irmin -y
  - make test
env:
  - OCAML_VERSION=4.05
addons:
  apt:
    update: true
